// Samurai Extended Format Legal Sets
export const SAMURAI_EXTENDED_SETS = [
  "samurai edition",
  "stronger than steel",
  "test of the emerald and jade championships",
  "honor's veil",
  "words and deeds",
  "samurai edition banzai",
  "the heaven's will",
  "glory of the empire",
  "the imperial gift 1",
  "death at koten",
  "celestial edition",
  "the imperial gift 2",
  "path of the destroyer",
  "the harbinger",
  "celestial edition 15",
  "the plague war",
  "the imperial gift 3",
  "battle of kyuden tonbo",
  "empire at war",
  "the dead of winter",
  "before the dawn",
  "forgotten legacy",
  "second city",
  "emperor edition",
  "embers of war",
  "the shadow's embrace",
  "seeds of decay",
  "honor and treachery",
  "emperor edition: gempukku",
  "torn asunder",
  "coils of madness",
  "gates of chaos",
  "aftermath",
  "a matter of honor",
  "ivory edition",
  "the coming storm",
  "a line in the sand",
  "the new order",
  "the currency of war",
  "twenty festivals",
  "thunderous acclaim",
  "evil portents",
];

// L5R Keywords - Comprehensive list for filtering
export const L5R_KEYWORDS = [
  "Imperial",
  "Unique",
  "One-Handed",
  "Tetsubo",
  "Weapon",
  "Pirate",
  "Personality",
  "Samurai",
  "Yojimbo",
  "Two-Handed",
  "Shadowlands",
  "Nonhuman",
  "Goblin",
  "Scout",
  "Oni",
  "Political",
  "Temple",
  "Monk",
  "Market",
  "Gold.",
  "Fire",
  "Shugenja",
  "Ninja",
  "Home",
  "Reserve",
  "Interrupt",
  "Limited",
  "Conqueror",
  "Crane Clan",
  "Dragon Clan",
  "Phoenix Clan",
  "Scorpion Clan",
  "Dynasty",
  "Crab Clan",
  "Lion Clan",
  "Mantis Clan",
  "Spider Clan",
  "Unicorn Clan",
  "Tactician",
  "Air",
  "Cavalry",
  "Destined",
  "Clans",
  "Expendable",
  "Conspiracy",
  "Battle/Open",
  "Kharmic",
  "Ancestor",
  "Spirit",
  "Clout",
  "Economic",
  "Forest",
  "Abomination",
  "Naga",
  "Champion",
  "Pearl",
  "Asp",
  "Cobra",
  "Experienced",
  "Contrictor",
  "Commander",
  "Spear",
  "Corrupted",
  "Fealty.",
  "Ashigaru",
  "Earth",
  "Village",
  "Fortification",
  "Barracks",
  "Library",
  "Sincerity",
  "Port",
  "Jade",
  "Viillage",
  "Court",
  "Mine",
  "Retainer",
  "Siege",
  "Resilient",
  "Cruel",
  "Magistrate",
  "Kolat",
  "Artisan",
  "Courtier",
  "Duelist",
  "Kensai",
  "Tatooed",
  "Historian",
  "Beastmaster",
  "Hero",
  "Thunder",
  "Naval",
  "Alchemist",
  "Void",
  "Inquisitor",
  "Master",
  "Loyal",
  "Water",
  "Tejina",
  "Lies",
  "Tairao",
  "Undead",
  "Greensnake",
  "Kumo",
  "Warlord",
  "Savior",
  "Maiden",
  "Paragon",
  "Ronin",
  "Mercenary",
  "Courage",
  "Cat",
  "Ogre",
  "Armor",
  "Peasant",
  "Sword",
  "Staff",
  "Chain",
  "Obsidian",
  "Terrain",
  "House",
  "Stable",
  "Inexperienced",
  "Insane",
  "ExperiencedCW",
  "Maho",
  "Dynasty:",
  "Bushi",
  "Festival",
  "Legacy",
  "Dojo",
  "Renew",
  "Farm",
  "Chameleon",
  "Constrictor",
  "Berserker",
  "Tadama",
  "Gunso",
  "Governor",
  "Braggart",
  "Tattooed",
  "Higaru",
  "Deathseeker",
  "Elite",
  "Daimyo",
  "Sociopath",
  "Kuroiban",
  "Cultist",
  "Bloodspeaker",
  "Enlightened",
  "Assassin",
  "Geisha",
  "Priest",
  "Kami",
  "Bandit",
  "Knife",
  "Bow",
  "Polearm",
  "Gaijin",
  "Osano-Wo",
  "Purified",
  "Akasha",
  "Brawler",
  "Drunkard",
  "Hunter",
  "Harrier",
  "Saboteur",
  "Poet",
  "Kenshinzen",
  "Yamabushi",
  "Sodan-Senzo",
  "Singular",
  "Skull",
  "Tessen",
  "Handed",
  "Ruin",
  "Horror",
  "Danna-sama",
  "Infiltrator",
  "Keirei",
  "Sato",
  "Scroll",
  "Standard",
  "Fallen",
  "Enforcer",
  "Kobun",
  "Hag",
  "Smuggler",
  "Firearm",
  "Ichido",
  "Edict",
  "Castle",
  "Kuniken",
];

// Card Types for deck categorization
export const CARD_TYPES = {
  DYNASTY: ["personality", "holding", "celestial", "region", "event"],
  FATE: ["strategy", "spell", "item", "follower", "ring"],
};

// Deck validation rules
export const DECK_RULES = {
  MIN_DYNASTY: 40,
  MIN_FATE: 40,
  MAX_COPIES: 3,
  MAX_STRONGHOLD: 1,
  MAX_SENSEI: 1,
};

// Clan colors for UI
export const CLAN_COLORS = {
  Crab: { bg: "bg-blue-50", text: "bg-blue-600", border: "border-blue-200" },
  Crane: { bg: "bg-gray-50", text: "bg-gray-600", border: "border-gray-200" },
  Dragon: {
    bg: "bg-green-50",
    text: "bg-green-600",
    border: "border-green-200",
  },
  Lion: {
    bg: "bg-yellow-50",
    text: "bg-yellow-600",
    border: "border-yellow-200",
  },
  Mantis: { bg: "bg-lime-50", text: "bg-lime-600", border: "border-lime-200" },
  Phoenix: { bg: "bg-red-50", text: "bg-red-500", border: "border-red-200" },
  Scorpion: {
    bg: "bg-purple-50",
    text: "bg-purple-600",
    border: "border-purple-200",
  },
  Spider: {
    bg: "bg-slate-50",
    text: "bg-slate-600",
    border: "border-slate-200",
  },
  Unicorn: { bg: "bg-pink-50", text: "bg-pink-600", border: "border-pink-200" },
};
